### ISSUE TITLE
TypeError: _reactNativeTesseractOcr.default.recognize is not a function

### ISSUE THREAD

**Issue by asadMumtaz-YSTL** [jonathanpalma/react-native-tesseract-ocr#141]
**Describe the bug**
After choosing image from phone gallery, I face this issue 
**Issue: ** 

TypeError: _reactNativeTesseractOcr.default.recognize is not a function
    at _callee$ (RN_ocr.js:24:36)
    at tryCatch (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at tryCatch (regeneratorRuntime.js:86:17)
    at invoke (regeneratorRuntime.js:124:20)
    at regeneratorRuntime.js:148:11
    at tryCallTwo (core.js:45:5)
    at doResolve (core.js:200:13)
    at new Promise (core.js:66:3)
    at callInvokeWithMethodAndArg (regeneratorRuntime.js:147:16)
    at AsyncIterator._invoke (regeneratorRuntime.js:152:129)
    at AsyncIterator.next (regeneratorRuntime.js:117:21)
    at exports.async (regeneratorRuntime.js:238:63)
    at _callee (RN_ocr.js:24:36)
    at eval (RN_ocr.js:24:5) '\n    at RN_OCR (http://localhost:8081/app/screens/Messages/container/RN_ocr.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:42:41)\n    at SceneView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166132:36)\n    at RCTView\n    at AnimatedComponent (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:70238:9)\n    at AnimatedComponentWrapper\n    at RCTView\n    at AnimatedComponent (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:70238:9)\n    at AnimatedComponentWrapper\n    at Screen (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:173869:36)\n    at Card (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:174186:36)\n    at Container (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:174352:38)\n    at RCTView\n    at ScreenContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:173950:36)\n    at RCTView\n    at AnimatedComponent (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:70238:9)\n    at AnimatedComponentWrapper\n    at Handler (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:170023:38)\n    at StackViewLayout (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:173035:36)\n    at withOrientation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:168228:38)\n    at RCTView\n    at Transitioner (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:177011:36)\n    at StackView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:172802:36)\n    at Navigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:164114:38)\n    at KeyboardAwareNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:167804:38)\n    at SceneView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166132:36)\n    at RCTView\n    at RCTView\n    at ResourceSavingScene (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:179040:36)\n    at RCTView\n    at ScreenContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:173950:36)\n    at RCTView\n    at TabNavigationView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:177686:36)\n    at NavigationView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:177894:38)\n    at Navigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:164114:38)\n    at SceneView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166132:36)\n    at SwitchView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:166077:36)\n    at Navigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:164114:38)\n    at NavigationContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:167294:38)\n    at RCTView\n    at AppCallHeader (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:569789:36)\n    at ConnectFunction (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:234678:43)\n    at RCTView\n    at RCTView\n    at MenuProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:534662:9)\n    at PersistGate (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:746138:7)\n    at Provider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:234248:22)\n    at RCTView\n    at Root (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:155583:7)\n    at StyledComponent (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:109264:40)\n    at StyleProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:117325:36)\n    at App\n    at RCTView\n    at RCTView\n    at AppContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:77067:7)'

**Dependencies (please complete the following information):**
 - react: [16.13.1]
 - react-native: [0.63.4]
 - react-native-tesseract-ocr: [^2.0.3]

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/92986645/194576541-df139258-31fd-49c9-87c5-86ece6c405a0.png">

**Smartphone (please complete the following information):**
 - Device: [iPhone 13 pr]
 - OS: [iOS 15.5]

**Additional context**

**Comment by asadMumtaz-YSTL** [comment]
@jonathanpalma Can you explain?

**Comment by jonathanpalma** [comment]
Sorry, there is no support of this library on iOS at the moment

**Comment by soadtechdev** [comment]
Are there any plans to support ios at some point?
